# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/
# https://github.com/poole/poole/issues/99 suggests to disable the following:
#relative_permalinks: true

# Setup
title: 'Reproducible Research at AGILE'
tagline: 'Reproducible Research @ AGILE'
description: 'Workshop series and reproducibility initiative at the <a href="https://agile-online.org/index.php/conference/" title="conference websites">AGILE International Conference on Geographic Information Science</a>'
url: https://reproducible-agile.github.io
baseurl: /

keywords:
  - open access
  - open data
  - open source
  - reproducibility
  - reproducible research
  - giscience
  - gis
  - executable research
  - executable papers
  - one-click reproduce

author:
  name: 'workshop organization committee'
  url: https://reproducible-agile.github.io/

exclude: [README.md, Gemfile, Gemfile.lock, Makefile]

github:
  repo: https://github.com/reproducible-agile/reproducible-agile.github.io

# ribbon itself by https://github.com/simonwhitaker/github-fork-ribbon-css
ribbon:
  show: false
  text: 'RR Workshop 2019'
  url: 'https://reproducible-agile.github.io/2019/#registration'

plugins:
  - jekyll-sitemap
